### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by bombear-github** [aubreypwd/google-voice-mac#2]
The app opens fine, and looks just like it does on Safari. But it displays the following error: "the app or browser may not be secure. Try another browser". Otherwise, it looks very promising!

<img width="534" alt="Screen Shot 2020-11-25 at 10 11 07 PM" src="https://user-images.githubusercontent.com/58050895/100314283-27c28e00-2f6b-11eb-97a3-e4dccc0e8c14.png">

**Comment by dbble** [comment]
Same issue as bombear. Unable to log in. Looking forward to using this one day.

**Comment by aubreypwd** [comment]
Funny, I was able to login...I will give then a look when I have time. Thanks.

**Comment by aubreypwd** [comment]
I was able to confirm this bug and fix it. Will come out in a few minutes in 1.1.1

**Comment by aubreypwd** [comment]
@bombear-github https://github.com/aubreypwd/google-voice-mac/releases/tag/v1.1.1
